/**
 * MIT License.
 */
package com.soft9000.ICell;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;

/**
 * A Graphical Server that can be either (1) dropped onto a JFrame (NetBeans,
 * etc.) or (2) custom created for use using youe own client & metrics.
 *
 * @author Randall Nagy
 */
public class JPanCellGrid extends javax.swing.JPanel implements IGridServer {

    BufferedImage img = null;
    private IGridClient set = null;
    private CellSlicer slicer;
    private CellEnumerator zenum;
    private int paint_retry; // avoid potential repaint loop
    private final Point cached = new Point(-1, -1);

    /**
     * Creates new form JPanCellGrid
     *
     */
    public JPanCellGrid() {
        this(new BlankCellSet(), new CellSlicer(15, 15));

    }

    public JPanCellGrid(IGridClient set, CellSlicer slicer) {
        this.set = set;
        this.slicer = slicer;
        set.onRegister(this);
        initComponents();
    }

    /**
     * NULL parameters are okay.
     *
     * @param set
     * @param slicer
     */
    public void assign(IGridClient set, CellSlicer slicer) {
        if (set != null) {
            this.set = set;
        }
        if (slicer != null) {
            this.slicer = slicer;
        }
        img = null;
        this.repaint();
    }

    @Override
    public void update(Graphics gr) {
        paint(gr);
    }

    @Override
    public void paint(Graphics gr) {
        check();
        if (zenum.drawAll(img, set) == false) {
            img = null; // possibilites 
            if (paint_retry < 3) {
                this.repaint();
            }
            paint_retry++;
        } else {
            gr.drawImage(img, 0, 0, this);
            paint_retry = 0;
        }
    }

    private void check() {
        if (img == null) {
            newImage();
        }
    }

    private void newImage() {
        if (img == null) {
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize(); // possibilites 
            img = new BufferedImage(dim.width + 1, dim.height + 1, BufferedImage.TYPE_INT_ARGB);
        }
        if (zenum == null) {
            zenum = new CellEnumerator(this.getSize(), slicer);
        } else {
            zenum = new CellEnumerator(zenum.getArrayOrigin(), this.getSize(), slicer);
        }
        Dimension dim = this.getSize();
        Graphics igr = img.getGraphics();
        igr.fillRect(0, 0, dim.width, dim.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(java.awt.Color.white);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        manageClick(evt);
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        manageClick(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        manageClick(evt);
    }//GEN-LAST:event_formMouseReleased

    private CellImage locate(Point point) {
        check();

        CellImage info = zenum.findCell(img, point);
        if (info != null) {
            return info;
        }
        img = null; // possibilites 
        this.repaint();
        return null;
    }

    @Override
    public void update(ICellShape mode) {
        // TODO: Implement tracking / mouse shape "ghosting."        
    }

    @Override
    public int getArrayOrigin() {
        check();
        return this.zenum.getArrayOrigin();
    }

    @Override
    public void setArrayOrigin(int ss) {
        check();
        this.zenum.setArrayOrigin(ss);
    }

    /**
     * Resolving the dropped-mouse click problem: Monitoring several clicking
     * events insures that at least ONE of them will be received... also
     * de-bounces mouse clicks.
     *
     * @param evt
     */
    private void manageClick(MouseEvent evt) {
        Point pt = evt.getPoint();
        if (this.cached.equals(pt)) {
            return;
        }
        cached.x = pt.x;
        cached.y = pt.y;
        System.out.println("Click: " + evt.getPoint().toString());
        CellImage cell = locate(evt.getPoint());
        if (cell != null) {
            System.out.println("Located");
            set.onClicked(cell);
            this.getGraphics().drawImage(img, 0, 0, this);
        } else {
            System.out.println("Not Located");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
